export const adminLabels = {
  layout: {
    logo: 'ParkingOps',
    subtitle: 'Panel de administración',
    menuSection: 'Gestión',
    vehicles: 'Vehículos',
    spots: 'Plazas',
    tariffs: 'Tarifas',
    stays: 'Estancias',
    adminName: 'Álvaro Orta',
    adminRole: 'Administrador',
    collapseSidebar: 'Colapsar menú lateral',
    expandSidebar: 'Expandir menú lateral',
  },
  vehicles: {
    pageTitle: 'Vehículos',
    pageSubtitle: 'Administración · Vehículos',
    records: 'registros',
    newVehicle: 'Nuevo vehículo',
    searchPlaceholder: 'Buscar por matrícula...',
    filterLabel: 'Estado:',
    filterAll: 'Todos los estados',
    tableHeaders: {
      id: 'ID',
      plate: 'Matrícula',
      brandModel: 'Marca / Modelo',
      type: 'Tipo',
      status: 'Estado',
    },
    types: {
      car: 'Coche',
      carPmr: 'Coche PMR',
      motorbike: 'Moto',
    },
    status: {
      parked: 'Estacionado',
      outside: 'Fuera',
    },
    emptyState: 'No hay vehículos registrados en el sistema.',
    loading: 'Cargando...',
    error: 'Error al cargar los vehículos.',
  },
  spots: {
    pageTitle: 'Plazas',
    pageSubtitle: 'Administración · Plazas',
    records: 'registros',
    legend: {
      available: 'Libres',
      occupied: 'Ocupadas',
    },
    tableHeaders: {
      idNumber: 'ID / N.º Plaza',
      type: 'Tipo',
      status: 'Estado',
    },
    types: {
      standard: 'Estándar',
      disabled: 'Discapacitados',
      motorbike: 'Moto',
    },
    status: {
      available: 'Libre',
      occupied: 'Ocupada',
      unavailable: 'No Disponible',
    },
    emptyState: 'No hay plazas registradas en el sistema.',
    error: 'Ha ocurrido un error al cargar las plazas. Por favor, inténtalo de nuevo.',
  },
  tariffs: {
    pageTitle: 'Tarifas',
    pageSubtitle: 'Administración · Tarifas de Aparcamiento',
    createTariff: 'Crear tarifa',
    form: {
      title: 'Crear nueva tarifa',
      subtitle: 'Define los precios por minuto y condiciones según el tipo de vehículo',
      name: 'Nombre de la tarifa',
      namePlaceholder: 'Ej. Tarifa Coche Estándar',
      vehicleType: 'Tipo de Vehículo',
      pricePerMinute: 'Precio por minuto (€/min)',
      pricePerMinutePlaceholder: '0.05',
      estimatedPerHour: '€ / hora',
      description: 'Descripción',
      descriptionPlaceholder: 'Detalles u observaciones sobre la tarifa...',
      mandatoryHint: 'Los campos marcados con * son obligatorios.',
      cancel: 'Cancelar',
      submit: 'Crear tarifa',
      processing: 'Guardando...',
      types: {
        car: 'Coche (Estándar)',
        carPmr: 'Coche (PMR)',
        motorbike: 'Moto',
      },
    },
  },
  stays: {
    pageTitle: 'Estancias',
    pageSubtitle: 'Administración · Estancias',
    records: 'registros',
    searchPlaceholder: 'Buscar por matrícula...',
    filterLabel: 'Estado:',
    filterAll: 'Todos los estados',
    filterAllVehicleTypes: 'Todos los tipos',
    filterByStatus: 'Filtrar por estado',
    filterByVehicleType: 'Filtrar por tipo de vehículo',
    tableHeaders: {
      plate: 'Matrícula',
      spot: 'Plaza',
      tariff: 'Tarifa',
      checkIn: 'Entrada',
      checkOut: 'Salida',
      total: 'Importe',
      status: 'Estado',
    },
    vehicleTypes: {
      CAR: 'Coche',
      CAR_PMR: 'Coche PMR',
      MOTORBIKE: 'Moto',
    },
    status: {
      inProgress: 'En curso',
      finished: 'Finalizada',
      cancelled: 'Cancelada',
    },
    nullValues: {
      checkOutInProgress: 'En curso',
      checkOutCancelled: 'Cancelada',
      checkOutMissing: '—',
      totalPending: 'Pendiente',
      totalNotApplicable: '—',
    },
    viewTicket: 'Ver ticket',
    viewTicketUnavailable: 'Ticket no disponible',
    emptyState: 'No hay estancias registradas en el sistema.',
    noResults: 'No se encontraron estancias con los filtros aplicados.',
    clearFilters: 'Limpiar filtros',
    loading: 'Cargando estancias...',
    error: 'Error al cargar las estancias.',
    pagination: {
      show: 'Mostrar',
      previous: 'Anterior',
      next: 'Siguiente',
      recordsPerPage: 'Registros por página',
      records: 'registros',
    },
  },
  form: {
    title: 'Registrar vehículo',
    subtitle: 'Alta en el registro · la plaza seleccionada se marcará como ocupada',
    idAssigned: 'ID Asignado',
    idAssignedHint: 'Generado automáticamente · secuencial',
    plate: 'Matrícula',
    plateHint: 'Formato: 4 dígitos + 3 letras',
    type: 'Tipo',
    brand: 'Marca',
    model: 'Modelo',
    color: 'Color',
    doors: 'Puertas',
    hasSideCar: 'Tiene sidecar',
    mandatoryHint: 'Los campos marcados con * son obligatorios.',
    cancel: 'Cancelar',
    submit: 'Registrar vehículo',
    processing: 'Procesando...',
    placeholder: {
      plate: '1234 ABC',
      brand: 'Seat',
      model: 'León',
      color: 'Blanco',
    },
  },
}
