export const adminLabels = {
  layout: {
    logo: 'ParkingOps',
    subtitle: 'Panel de administración',
    menuSection: 'Gestión',
    vehicles: 'Vehículos',
    spots: 'Plazas',
    tariffs: 'Tarifas',
    stays: 'Estancias',
    tickets: 'Tickets',
    adminName: 'Álvaro Orta',
    adminRole: 'Administrador',
    collapseSidebar: 'Colapsar menú lateral',
    expandSidebar: 'Expandir menú lateral',
  },
  vehicles: {
    pageTitle: 'Vehículos',
    pageSubtitle: 'Administración · Vehículos',
    records: 'registros',
    newVehicle: 'Nuevo vehículo',
    searchPlaceholder: 'Buscar por matrícula...',
    filterLabel: 'Estado:',
    filterAll: 'Todos los estados',
    tableHeaders: {
      id: 'ID',
      plate: 'Matrícula',
      brandModel: 'Marca / Modelo',
      type: 'Tipo',
      status: 'Estado',
      actions: 'Acciones',
    },
    actions: {
      deactivate: 'Dar de baja',
      activate: 'Reactivar',
      confirmDeactivateTitle: '¿Dar de baja vehículo?',
      confirmDeactivateMessage: '¿Estás seguro de que deseas dar de baja este vehículo? Pasará a estar inactivo en el sistema.',
      confirmActivateTitle: '¿Reactivar vehículo?',
      confirmActivateMessage: '¿Deseas volver a activar este vehículo en el sistema?',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      processing: 'Procesando...',
      errorUpdate: 'Error al cambiar el estado del vehículo.',
      selectedVehicle: 'Vehículo seleccionado:',
      active: 'Activo',
      inactive: 'Inactivo',
    },
    types: {
      car: 'Coche',
      carPmr: 'Coche PMR',
      motorbike: 'Moto',
    },
    status: {
      parked: 'Estacionado',
      outside: 'Fuera',
    },
    emptyState: 'No hay vehículos registrados en el sistema.',
    loading: 'Cargando...',
    error: 'Error al cargar los vehículos.',
  },
  spots: {
    pageTitle: 'Plazas',
    pageSubtitle: 'Administración · Plazas',
    records: 'registros',
    legend: {
      available: 'Libres',
      occupied: 'Ocupadas',
    },
    tableHeaders: {
      idNumber: 'ID / N.º Plaza',
      type: 'Tipo',
      status: 'Estado',
    },
    types: {
      standard: 'Estándar',
      disabled: 'Discapacitados',
      motorbike: 'Moto',
    },
    status: {
      available: 'Libre',
      occupied: 'Ocupada',
      unavailable: 'No Disponible',
    },
    maintenance: {
      action: 'Mantenimiento',
      restoreAction: 'Restaurar',
      confirmTitle: '¿Poner plaza en mantenimiento?',
      confirmMessage: '¿Estás seguro de que deseas marcar esta plaza como NO DISPONIBLE? No se podrán aparcar vehículos en ella hasta que se restaure.',
      restoreTitle: '¿Restaurar plaza?',
      restoreMessage: '¿Deseas marcar esta plaza como LIBRE nuevamente?',
      selectedSpot: 'Plaza seleccionada:',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      processing: 'Procesando...',
      errorUpdate: 'Error al cambiar el estado de la plaza.',
    },
    emptyState: 'No hay plazas registradas en el sistema.',
    error: 'Ha ocurrido un error al cargar las plazas. Por favor, inténtalo de nuevo.',
  },
  tariffs: {
    pageTitle: 'Tarifas',
    pageSubtitle: 'Administración · Tarifas de Aparcamiento',
    createTariff: 'Crear tarifa',
    records: 'registros',
    emptyState: 'No hay tarifas registradas en el sistema.',
    error: 'Error al cargar las tarifas.',
    tableHeaders: {
      name: 'Nombre',
      vehicleType: 'Tipo de Vehículo',
      basePrice: 'Precio Base (€)',
      pricePerMinute: 'Precio / Min (€/min)',
      status: 'Estado',
      actions: 'Acciones',
    },
    status: {
      active: 'Activa',
      inactive: 'Inactiva',
    },
    actions: {
      edit: 'Editar',
      deactivate: 'Desactivar',
      activate: 'Activar',
      delete: 'Eliminar',
      confirmDeleteTitle: '¿Eliminar tarifa?',
      confirmDeleteMessage: 'Esta acción eliminará la tarifa del sistema de forma permanente. ¿Deseas continuar?',
      cancel: 'Cancelar',
    },
    form: {
      title: 'Crear nueva tarifa',
      editTitle: 'Editar tarifa',
      subtitle: 'Define el precio base, precio por minuto y condiciones según el tipo de vehículo',
      editSubtitle: 'Modifica los precios y la configuración de la tarifa seleccionada',
      name: 'Nombre de la tarifa',
      namePlaceholder: 'Ej. Tarifa Coche Estándar',
      vehicleType: 'Tipo de Vehículo',
      basePrice: 'Precio base (€)',
      basePricePlaceholder: '1.50',
      pricePerMinute: 'Precio por minuto (€/min)',
      pricePerMinutePlaceholder: '0.05',
      estimatedPerHour: '€ / hora',
      mandatoryHint: 'Los campos marcados con * son obligatorios.',
      cancel: 'Cancelar',
      submit: 'Crear tarifa',
      submitEdit: 'Guardar cambios',
      processing: 'Guardando...',
      types: {
        car: 'Coche (Estándar)',
        carPmr: 'Coche (PMR)',
        motorbike: 'Moto',
      },
    },
    activeTariffLookup: {
      title: 'Tarifa Activa por Tipo de Vehículo',
      selectLabel: 'Seleccionar tipo:',
      activeBadge: 'Tarifa Vigente',
      basePrice: 'Precio Base',
      pricePerMinute: 'Precio / Minuto',
      loading: 'Consultando tarifa activa...',
      notFound: 'No hay una tarifa activa configurada para este tipo de vehículo.',
      error: 'Error al consultar la tarifa activa.',
    },
  },
  stays: {
    pageTitle: 'Estancias',
    pageSubtitle: 'Administración · Estancias',
    records: 'registros',
    searchPlaceholder: 'Buscar por matrícula...',
    filterLabel: 'Estado:',
    filterAll: 'Todos los estados',
    filterAllVehicleTypes: 'Todos los tipos',
    filterByStatus: 'Filtrar por estado',
    filterByVehicleType: 'Filtrar por tipo de vehículo',
    tableHeaders: {
      plate: 'Matrícula',
      spot: 'Plaza',
      tariff: 'Tarifa',
      checkIn: 'Entrada',
      checkOut: 'Salida',
      total: 'Importe',
      status: 'Estado',
    },
    vehicleTypes: {
      CAR: 'Coche',
      CAR_PMR: 'Coche PMR',
      MOTORBIKE: 'Moto',
    },
    status: {
      inProgress: 'En curso',
      finished: 'Finalizada',
      cancelled: 'Cancelada',
    },
    nullValues: {
      checkOutInProgress: 'En curso',
      checkOutCancelled: 'Cancelada',
      checkOutMissing: '—',
      totalPending: 'Pendiente',
      totalNotApplicable: '—',
    },
    viewTicket: 'Ver ticket',
    viewTicketUnavailable: 'Ticket no disponible',
    emptyState: 'No hay estancias registradas en el sistema.',
    noResults: 'No se encontraron estancias con los filtros aplicados.',
    clearFilters: 'Limpiar filtros',
    loading: 'Cargando estancias...',
    error: 'Error al cargar las estancias.',
    pagination: {
      show: 'Mostrar',
      previous: 'Anterior',
      next: 'Siguiente',
      recordsPerPage: 'Registros por página',
      records: 'registros',
    },
  },
  tickets: {
    pageTitle: 'Tickets',
    pageSubtitle: 'Administración · Tickets emitidos',
    records: 'registros',
    searchPlaceholder: 'Buscar por ID de ticket o estancia...',
    dateFromLabel: 'Desde:',
    dateToLabel: 'Hasta:',
    clearDates: 'Limpiar fechas',
    tableHeaders: {
      uniqueId: 'ID Ticket',
      stayId: 'ID Estancia',
      issuedAt: 'Fecha Emisión',
      totalAmount: 'Importe Total',
    },
    emptyState: 'No hay tickets registrados en el sistema.',
    noResults: 'No se encontraron tickets con los filtros aplicados.',
    clearFilters: 'Limpiar filtros',
    loading: 'Cargando tickets...',
    error: 'Error al cargar los tickets.',
    pagination: {
      show: 'Mostrar',
      previous: 'Anterior',
      next: 'Siguiente',
      recordsPerPage: 'Registros por página',
      records: 'registros',
    },
  },
  form: {
    title: 'Registrar vehículo',
    subtitle: 'Alta en el registro · la plaza seleccionada se marcará como ocupada',
    idAssigned: 'ID Asignado',
    idAssignedHint: 'Generado automáticamente · secuencial',
    plate: 'Matrícula',
    plateHint: 'Formato: 4 dígitos + 3 letras',
    type: 'Tipo',
    brand: 'Marca',
    model: 'Modelo',
    color: 'Color',
    doors: 'Puertas',
    hasSideCar: 'Tiene sidecar',
    mandatoryHint: 'Los campos marcados con * son obligatorios.',
    cancel: 'Cancelar',
    submit: 'Registrar vehículo',
    processing: 'Procesando...',
    placeholder: {
      plate: '1234 ABC',
      brand: 'Seat',
      model: 'León',
      color: 'Blanco',
    },
  },
}
