export const adminLabels = {
  layout: {
    logo: 'ParkingOps',
    subtitle: 'Panel de administración',
    menuSection: 'Gestión',
    vehicles: 'Vehículos',
    spots: 'Plazas',
    adminName: 'Álvaro Orta',
    adminRole: 'Administrador',
  },
  vehicles: {
    pageTitle: 'Vehículos',
    pageSubtitle: 'Administración · Vehículos',
    records: 'registros',
    newVehicle: 'Nuevo vehículo',
    tableHeaders: {
      id: 'ID',
      plate: 'Matrícula',
      brandModel: 'Marca / Modelo',
      type: 'Tipo',
      status: 'Estado',
    },
    types: {
      car: 'Coche',
      carPmr: 'Coche PMR',
      motorbike: 'Moto',
    },
    status: {
      parked: 'Estacionado',
      outside: 'Fuera',
    },
    emptyState: 'No hay vehículos registrados en el sistema.',
    loading: 'Cargando...',
    error: 'Error al cargar los vehículos.',
  },
  spots: {
    pageTitle: 'Plazas',
    pageSubtitle: 'Administración · Plazas',
    records: 'registros',
    legend: {
      available: 'Libres',
      occupied: 'Ocupadas',
    },
    tableHeaders: {
      idNumber: 'ID / N.º Plaza',
      type: 'Tipo',
      status: 'Estado',
    },
    types: {
      standard: 'Estándar',
      disabled: 'Discapacitados',
      motorbike: 'Moto',
    },
    status: {
      available: 'Libre',
      occupied: 'Ocupada',
      unavailable: 'No Disponible',
    },
    emptyState: 'No hay plazas registradas en el sistema.',
    error: 'Ha ocurrido un error al cargar las plazas. Por favor, inténtalo de nuevo.',
  },
  form: {
    title: 'Registrar vehículo',
    subtitle: 'Alta en el registro · la plaza seleccionada se marcará como ocupada',
    idAssigned: 'ID Asignado',
    idAssignedHint: 'Generado automáticamente · secuencial',
    plate: 'Matrícula',
    plateHint: 'Formato: 4 dígitos + 3 letras',
    type: 'Tipo',
    brand: 'Marca',
    model: 'Modelo',
    color: 'Color',
    doors: 'Puertas',
    hasSideCar: 'Tiene sidecar',
    mandatoryHint: 'Los campos marcados con * son obligatorios.',
    cancel: 'Cancelar',
    submit: 'Registrar vehículo',
    processing: 'Procesando...',
    placeholder: {
      plate: '1234 ABC',
      brand: 'Seat',
      model: 'León',
      color: 'Blanco',
    },
  },
}
