# Reverse proxy por prefijo hacia cada microservicio (misma red Docker
# 'parking-shared') + servido de la SPA con fallback a index.html para el
# router del cliente.

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /v1/vehicles {
        proxy_pass http://vehicle-service:8080;
    }

    location /v1/spots {
        proxy_pass http://spot-service:8080;
    }

    location /v1/tariffs {
        proxy_pass http://tariff-service:8080;
    }

    location /v1/stays {
        proxy_pass http://stay-service:8080;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
